name: isp_management
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.1
  #dio: ^4.0.4
  shared_preferences: ^2.1.0
  intl: ^0.18.1
  fluttertoast: ^8.1.1
  staggered_grid_view_flutter: ^0.0.4
  #flutter_share: ^2.0.0
  url_launcher: ^6.1.10
  flutter_svg: ^1.1.0
  path_provider: ^2.0.9
  http: ^0.13.4
  cached_network_image: ^3.2.0
  firebase_messaging: ^11.4.4
  device_info_plus: ^3.2.3
  uuid: ^3.0.6
  sqlite3_flutter_libs: ^0.5.13
  flutter_network_connectivity: ^0.0.6
  carousel_slider: ^4.1.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_cache_manager: ^3.3.0
  lottie: ^2.3.0
  animated_text_kit: ^4.2.2
  image_picker: ^0.8.7+4
  shimmer_animation: ^2.0.0
#  share_social_network: ^1.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/language/
    - assets/svg/
    - assets/lottie/